{% set name = "fbprophet" %}
{% set version = "0.1.post1" %}
{% set sha256sum = "b70808a1c58ec9883e07bf92deed51b44f572064057a35ee8409bca195ed41af" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}
  patches:
    # Models are not fully compatible with pystan<2.10 (assignment operator).
    - pystan-28-compat.patch

build:
  number: 1
  script: python setup.py install -q --single-version-externally-managed --record=record.txt
  skip: True  # [not x86_64]
  features:
    - vc14  # [win and py35]
    - vc14  # [win and py36]

requirements:
  build:
    - python
    - setuptools
    - pystan >=2.8
    # Pystan models depend on numpy and as they are compiled and pickled we
    # need to pin numpy version.
    - numpy x.x

  run:
    - python
    # setuptools is required for pkg_resources
    - setuptools
    - pystan >=2.8
    - numpy x.x
    - numpy
    - pandas
    - matplotlib

about:
  home: https://facebookincubator.github.io/
  license: BSD 3-clause
  #license_file: LICENSE
  summary: Automatic Forecasting Procedure
  description: |
    Implements a procedure for forecasting time series data based on an
    additive model where non-linear trends are fit with yearly and weekly
    seasonality, plus holidays. It works best with daily periodicity data with
    at least one year of historical data. Prophet is robust to missing data,
    shifts in the trend, and large outliers.
  doc_url: https://facebookincubator.github.io/prophet/docs/quick_start.html
  dev_url: https://github.com/facebookincubator/prophet

extra:
  recipe-maintainers:
    - rolando
