{% set name = "pystan-model-test" %}
{% set version = "0.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 0
  features:
    - vc9   # [win and py27]
    - vc14  # [win and py35]
    - vc14  # [win and py36]
  detect_binary_files_with_prefix: False

requirements:
  run:
    - pystan >=2.14
